server:
  port: 8080

spring:
  application:
    name: kafka-demo
  cloud:
    function:
      definition: consumer;supplier;analytics
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        # Producer
        producer-out-0:
          destination: events

        # Consumer
        consumer-in-0:
          destination: events
          group: consumer-group

        # Supplier
        supplier-out-0:
          destination: data-stream

        # Analytics Consumer
        analytics-in-0:
          destination: data-stream
          group: analytics-group

      poller:
        fixed-delay: 2000